### PR TITLE
Accept custom header template url for table-lite and table-ahax

### PR DESCRIPTION
**Pull request by thecodejack**

### CODE REVIEW

**Comment by thecodejack** [comment]
@slawomirdie @kashjs

**Comment by demee** [comment]
Nice one, would you add it to the documentation / demos as well as an example? Thank you.

**Comment by thecodejack** [comment]
sure

**Comment by thecodejack** [comment]
@slawomirdie done

**Comment by dkadrios** [comment]
Cool -- let's get this into the pipe please.

**Pull request merged**
