### PR TITLE
Allow to prevent drag on certain child elements

### PR DESCRIPTION
**Pull request by manudwarf**
Issue at hand (see updated doc file):

We want the user to be able to click on certain elements that are inside of a draggable element (ie. a link).

This proposed feature brings a CSS class `.ad-prevent-drag`. Adding this class on any element prevents dragging from happening.

I would happy to provide a test case, but the e2e file is completely empty at the moment.

Edit: Also added, children elements of `.ad-prevent-drag` do not trigger drag&drop.

### CODE REVIEW

**Comment by kashjs** [comment]
@bomsy can you review this?

**Comment by bomsy** [comment]
LGTM

**Comment by kashjs** [comment]
can we make this an attribute instead of class? it would be more inline with angular way of doing things.

**Comment by manudwarf** [comment]
Makes sense. What is the file that contains the reference for draggable? I couldn't find it.

**Comment by kashjs** [comment]
it is in `docs/moduleDefinitions.js`. Don't worry, i will take care of documenting this.

**Comment by kashjs** [comment]
Thanks very much for nice improvements. This definitely stabilizes drag & drop component.

**Comment by kashjs** [comment]
i have added the documentation.

**Comment by kashjs** [comment]
v2.2.6 has been released with the improvements https://github.com/Adaptv/adapt-strap/releases/tag/2.2.6

**Pull request merged**
