### PR TITLE
Added if condition to check for column header availability.

### PR DESCRIPTION
**Pull request by SubhaBabu**
if empty displayname, add column index as classname else add column header as classname.

### CODE REVIEW

**Comment by SubhaBabu** [comment]
Hi, 

Any updates on this pull request?

Thanks
Subha

**Comment by kashjs** [comment]
it has been merged to master

**Comment by kashjs** [comment]
give me a few hours. I will look into it. Thanks.

**Comment by demee** [comment]
@SubhaBabu If we can use nth-child() for styling (which is actually very good suggestion), do we even need to add classes with $index? Shall we skip noise all together?

**Comment by SubhaBabu** [comment]
Hi Slawomir, We discussed about this implemenation in my previous pull
request. To recap: we use table-lite and table-ajax for dynamic content
where we cannot decide which column will have description or id, etc. It is
determined based on filter. For example, we need word wrap for description
column, but not other columns. Is there any other (simple way) to do it
without an unique class?

Thanks
Subha

On Tue, Dec 8, 2015 at 7:55 AM, Slawomir Demichowicz <
notifications@github.com> wrote:

> @SubhaBabu <https://github.com/SubhaBabu> If we can use nth-child() for
> styling (which is actually very good suggestion), do we even need to add
> classes with $index? Shall we skip noise all together?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adaptv/adapt-strap/pull/223#issuecomment-162872167>.
>



-- 
Thanks,

Subha

**Comment by demee** [comment]
Ok, gotcha. In this case it makes sense. Now... Kash where are you? Merge !

**Comment by kashjs** [comment]
there is something wrong with this pull request.
you need to rebase with latest develop

**Comment by SubhaBabu** [comment]
Rebased my branch. Please let me know when you can merge.

Thanks


On Tue, Dec 8, 2015 at 9:01 PM, Kash Patel <notifications@github.com> wrote:

> there is something wrong with this pull request.
> you need to rebase with latest develop
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adaptv/adapt-strap/pull/223#issuecomment-163082224>.
>



-- 
Thanks,

Subha

**Comment by kashjs** [comment]
you need to do this while you are on your local fork branch:
```
git remote add upstream https://github.com/Adaptv/adapt-strap.git
git fetch upstream
git merge upstream/master
``

**Comment by SubhaBabu** [comment]
I merged. please confirm.


On Wed, Dec 9, 2015 at 11:58 AM, Kash Patel <notifications@github.com>
wrote:

> you need to do this while you are on your local fork branch:
>
> git remote add upstream https://github.com/Adaptv/adapt-strap.git
> git fetch upstream
> git merge upstream/master
> ``
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adaptv/adapt-strap/pull/223#issuecomment-163324036>.
>



-- 
Thanks,

Subha

**Pull request merged**
