### PR TITLE
Bug fix and additions

### PR DESCRIPTION
**Pull request by brianchance**
- Fix apply filter bug where filter contains a ':' i.e. date: mm/dd/yyyy hh:mm a
- Add config for tableClasses
- Add css to ajax table pagination
- Add tableFixedHeight to ajax table

### CODE REVIEW

**Comment by kashjs** [comment]
One quick suggestion.

similar to iconClasses, we should create another object called componentClasses. Like this:

```javascript
componentClasses = {
    tableClass = "table"
}
```

**Comment by brianchance** [comment]
Changed.

**Comment by brianchance** [comment]
Are we waiting on the travis build? It is complaining about not being able to find the module 'vinyl'. Can you requeue the build?

**Comment by brianchance** [comment]
Added expand callback to tablelite based on #160

**Comment by kashjs** [comment]
HI Brian,

What does tableFixedHeight do?

**Comment by brianchance** [comment]
Sets the grid at a specific height. With max-heigh, if the table fits in less space, it shrinks up. So, with fixed height, if you have two grids stacked it keeps them at a constant height.

**Comment by kashjs** [comment]
Can you also add that to table lite? We need to keep table-lite and table-ajax similar. I know it is painful to maintain two different components with similar functionality. I am working on merging them into one. But until then, we need to keep the functionalities in sync.

**Comment by brianchance** [comment]
The tableFixedHeight for tablelite was in the last PR (#159).

**Comment by kashjs** [comment]
Oh really. Sorry about false flag... I will merge it shortly. Also I think this is good time for minor release. Unless you have anything else to add...

**Comment by brianchance** [comment]
I realized that visible wasn't used in the expand template. I made visible columns an array and updated both tablelite and tableajax.

Hopefully that will do me for a while.

**Comment by kashjs** [comment]
you need to run validation.. seems like there are errors.

**Comment by kashjs** [comment]
`gulp validate`

**Comment by kashjs** [comment]
v2.1.5 has been released.

**Comment by brianchance** [comment]
Thanks Kash.

**Pull request merged**
